version: '3'
services:
  nginx:
   container_name: some-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   - ./src:/app/static
   depends_on:
   - app
 
  mysql:
   container_name: some-mysql
   image: mariadb:10.7
   volumes:
    - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
   environment:
    MYSQL_DATABASE: meetsapp
    MYSQL_ROOT_PASSWORD: '1324'
    MYSQL_ROOT_HOST: root
   ports:
    - "3306:3306"
   restart: always
  
  app:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql
